name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 1
      id: test-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 1
        setup-command: g++ main.cpp fractionTypeImp.cpp -o program
        command: "./program"
        input: |-
          2/3
          1/2
        expected-output: |-
          2 / 3 == 1 / 2 = 0
          2 / 3 != 1 / 2 = 1
          2 / 3 <= 1 / 2 = 0
          2 / 3 < 1 / 2 = 0
          2 / 3 >= 1 / 2 = 1
          2 / 3 > 1 / 2 = 1
          2 / 3 + 1 / 2 = 7 / 6
          2 / 3 * 1 / 2 = 2 / 6
          2 / 3 - 1 / 2 = 1 / 6
          (2 / 3) / (1 / 2) = 4 / 3
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: g++ main.cpp fractionTypeImp.cpp -o program
        command: "./program"
        input: |-
          3/4
          5/8
        expected-output: |-
          3 / 4 == 5 / 8 = 0
          3 / 4 != 5 / 8 = 1
          3 / 4 <= 5 / 8 = 0
          3 / 4 < 5 / 8 = 0
          3 / 4 >= 5 / 8 = 1
          3 / 4 > 5 / 8 = 1
          3 / 4 + 5 / 8 = 44 / 32
          3 / 4 * 5 / 8 = 15 / 32
          3 / 4 - 5 / 8 = 4 / 32
          (3 / 4) / (5 / 8) = 24 / 20
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Test 3
      id: test-3
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 3
        setup-command: g++ main.cpp fractionTypeImp.cpp -o program
        command: "./program"
        input: |-
          4/5
          4/5
        expected-output: |-
          4 / 5 == 4 / 5 = 1
          4 / 5 != 4 / 5 = 0
          4 / 5 <= 4 / 5 = 1
          4 / 5 < 4 / 5 = 0
          4 / 5 >= 4 / 5 = 1
          4 / 5 > 4 / 5 = 0
          4 / 5 + 4 / 5 = 40 / 25
          4 / 5 * 4 / 5 = 16 / 25
          4 / 5 - 4 / 5 = 0 / 25
          (4 / 5) / (4 / 5) = 20 / 20
        comparison-method: contains
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-1_RESULTS: "${{steps.test-1.outputs.result}}"
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-3_RESULTS: "${{steps.test-3.outputs.result}}"
      with:
        runners: test-1,test-2,test-3
